..\..\parser sample4.c > sample4.out
..\..\parser array.c > array.out
..\..\parser correct.c > correct.out
..\..\parser func.c > func.out
..\..\parser var.c > var.out
..\..\parser more1.c > more1.out
..\..\parser more2.c > more2.out
..\..\parser more3.c > more3.out
..\..\parser more4.c > more4.out
..\..\parser more5.c > more5.out
